/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Moonwise (https://sketchfab.com/Moonwise)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/night-sky-aebbd4f5b37a4dfd8e3556de9084bae9
Title: Night sky
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import balloonScene from "./night_sky.glb";

const Balloon = ({ isRotating, setIsRotating, ...props }) => {
  const { nodes, materials } = useGLTF(balloonScene);

    useEffect(() => {
      if (materials.White) {
        materials.White.color.set("#ff0000"); // Set to red color
      }
      if (materials.Black) {
        materials.Black.color.set("#FFD700"); // Set to red color
      }
      // Repeat for other materials if necessary
    }, [materials]);

  return (
    <group {...props} dispose={null}>
      <group position={[0, -11.051, -4.906]} scale={[7.683, 5.769, 7.683]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.Black}
        />
      </group>
      <group
        position={[-9.653, -9.826, -4.77]}
        rotation={[0, 0, -0.373]}
        scale={1.911}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.Black}
        />
      </group>
      <group
        position={[0, 16.232, -4.906]}
        rotation={[0, 1.343, 0]}
        scale={[16.315, 17.967, 16.315]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.White}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials["Material.001"]}
        position={[9.319, -12.547, 14.91]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-6.5, 6.5, 6.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials.material_0}
        position={[19.008, -21.751, 3.116]}
        scale={4.451}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials["Material.001"]}
        position={[-2.279, 11.56, -25.772]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.866}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials["Material.001"]}
        position={[-5.769, -5.004, -24.141]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={2.343}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_21.geometry}
        material={materials["Material.001"]}
        position={[-7.509, -4.915, 23.286]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.989}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_23.geometry}
        material={materials["Material.001"]}
        position={[-2.615, 22.847, 16.968]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.989}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_25.geometry}
        material={materials["Material.001"]}
        position={[10.367, 0.068, 14.477]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.901}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_27.geometry}
        material={materials["Material.001"]}
        position={[7.6, -22.266, -22.539]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.436}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_29.geometry}
        material={materials["Material.001"]}
        position={[13.579, -3.15, -19.025]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.989}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_31.geometry}
        material={materials["Material.001"]}
        position={[13.579, 8.121, -27.849]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.989}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_33.geometry}
        material={materials["Material.001"]}
        position={[13.579, 16.203, -24.883]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.904}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_35.geometry}
        material={materials["Material.001"]}
        position={[13.579, 2.189, -22.065]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.255}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_37.geometry}
        material={materials["Material.001"]}
        position={[10.367, -7.718, 9.064]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_39.geometry}
        material={materials["Material.001"]}
        position={[13.579, -23.987, -15.317]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={2.338}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_41.geometry}
        material={materials["Material.001"]}
        position={[10.367, 0.513, 22.559]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_43.geometry}
        material={materials["Material.001"]}
        position={[3.115, -11.486, 27.884]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.421}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_45.geometry}
        material={materials["Material.001"]}
        position={[10.367, 18.457, 16.182]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_47.geometry}
        material={materials["Material.001"]}
        position={[3.115, 0.971, -26.839]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.421}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_49.geometry}
        material={materials["Material.001"]}
        position={[17.619, -2.232, 17.829]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.808}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_51.geometry}
        material={materials["Material.001"]}
        position={[-10.713, 17.152, -31.26]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={3.221}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_53.geometry}
        material={materials["Material.001"]}
        position={[-5.769, 2.292, -34.73]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={2.599}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_55.geometry}
        material={materials["Material.001"]}
        position={[3.153, 6.329, -23.744]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.76}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_57.geometry}
        material={materials["Material.001"]}
        position={[13.579, -4.725, -31.289]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.904}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_59.geometry}
        material={materials["Material.001"]}
        position={[13.579, 9.369, -34.172]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.904}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_61.geometry}
        material={materials["Material.001"]}
        position={[13.579, -4.832, -36.414]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.904}
      />
    </group>
  );
};

export default Balloon;

